### ISSUE TITLE
add a Finish() callback to CoordinatedActivityHandler 

### ISSUE THREAD

**Issue by sclasen** [sclasen/swfsm#75] opened 2015-07-20 21:37 UTC
this allows cleanup to occur after a task finsihes or fails /cc @dpiddy

**Comment by ryanwalls** [comment] 2016-02-08 19:11
Maybe #121 is a duplicate of this?

**Comment by sclasen** [comment] 2016-02-08 20:24
This is different I think. its roughly the equivalent of Cancel() but gets called after task success or failure.

**Comment by dpiddy** [comment] 2016-03-23 17:06
Closed by #154

**Closed by dpiddy** 2016-03-23 17:06 UTC
